MiniBlogDjango/blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.index, name = 'index'),
    path('articles/', views.ArticleListView.as_view(), name = 'articles'),
    path('article/<int:pk>', views.ArticleDetailView.as_view(), name = 'article-detail'),
    path('bloggers/', views.BloggerListView.as_view(), name = 'bloggers'),
    path('blogger/<int:pk>', views.BloggerDetailView.as_view(), name = 'blogger-detail'),
    path('myarticle/', views.MyArticleUserListView.as_view(), name = 'my-articles'),
    path('allarticle/', views.MyArticleAllUserListView.as_view(), name = 'all-articles'),
    path('register/', views.sign_up, name = 'register'),
    path('article/<int:pk>/update/', views.ArticleUpdate.as_view(), name = 'article_update'),
    path('article/<int:pk>/delete/', views.ArticleDelete.as_view(), name = 'article_delete'),
    path('blogger/<int:pk>/create/', views.ArticleCreate.as_view(), name = 'article_create'),
    path('article/<int:pk>/comment/create/', views.ArticleInstanceCreate.as_view(), name = 'comment_create'),
    path('article/<int:pk>/comment/delete/', views.ArticleInstanceDelete.as_view(), name = 'comment_delete'),
]

MiniBlogDjango/miniblog/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

from django.conf.urls import include
urlpatterns += [
    path('miniblog/', include('blog.urls')),
]

from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url = '/miniblog/')),
]

from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

MiniBlogDjango/blog/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Genre(models.Model):
    name = models.CharField(max_length=20, help_text='Enter a article genre (e.g. Gossip, Movie Function)') 

    def __str__(self):
        return self.name
#_______________________________________________________

class Blogger(models.Model):
    user = models.OneToOneField(User,on_delete=models.SET_NULL, null=True)

    SEX_CHOICE = (
        (0, 'Female'),
        (1, 'Male'),
    )
    sex = models.IntegerField(choices=SEX_CHOICE,default=1)
    
    date_of_birth= models.DateField(null=True, blank=True)


    class Meta:
        ordering = ['user']
        permissions = (("can_edit_all_SET", "can edit all"),)
        permissions = (("can_create_articles", "can write articles"),)

    def get_absolute_url(self):
        return reverse('blogger-detail', args=[str(self.id)])
    def __str__(self):
        return self.user.username
#_______________________________________________________

from django.urls import reverse
class Article(models.Model):
    blogger = models.ForeignKey(Blogger, on_delete=models.CASCADE,null=True)
    title = models.CharField(max_length=200)
    genre = models.ManyToManyField(Genre, help_text='Select a genre for this article')
    content = models.TextField(max_length=3000, help_text='Enter content of the article')
    issusing_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['issusing_time']

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('article-detail', args=[str(self.id)])
#_______________________________________________________

class ArticleInstance(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    commenter = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    comment = models.TextField(max_length=300, help_text='Enter comment of the article')
    post_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['post_time']

    def __str__(self):
        len_title=50
        if len(self.comment)>len_title:
            titlestring=self.comment[:len_title] + '...'
        else:
            titlestring=self.comment
        return titlestring

MiniBlogDjango/blog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class RegisterForm(UserCreationForm):

    username = forms.CharField(
        label = "帳號" ,
        widget = forms.TextInput(attrs={'placeholder' : 'user'})
    )

    email = forms.EmailField(
        label = "電子信箱",
        widget = forms.EmailInput(attrs={'placeholder' : 'email'})
    )

    password1 = forms.CharField(
        label = "密碼",
        widget = forms.PasswordInput(attrs={'placeholder' : 'password'})
    )

    password2 = forms.CharField(
        label = "密碼確認",
        widget = forms.PasswordInput(attrs={'placeholder' : 'password confirmation'})
    )

    class Meta: # 排序
        model = User
        fields = ('username', 'email', 'password1', 'password2') 

MiniBlogDjango/blog/views.py
from django.shortcuts import render

# Create your views here.

# front page
from .models import Article,Blogger, ArticleInstance, Genre
def index(request):
    num_articles = Article.objects.all().count()
    num_comments = ArticleInstance.objects.all().count()
    num_bloggers = Blogger.objects.all().count()
    num_genre = Genre.objects.all().count()

    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    context = {
        'num_articles' : num_articles,
        'num_comments' : num_comments,
        'num_bloggers' : num_bloggers,
        'num_genre' : num_genre,
        'num_visits' : num_visits
    }

    return render(request, 'index.html', context=context)

# List
from django.views import generic
class ArticleListView(generic.ListView):
    model = Article
    paginate_by = 10

class ArticleDetailView(generic.DetailView):
    model = Article
    paginate_by = 10

    def article_detail_view(request, primary_key):
        try:
            article = Article.objects.get(pk = primary_key)
        except:
            raise Http404('Article does not exist')

        return render(request, 'blog/article_detail.html', context={'article':article})

class BloggerListView(generic.ListView):
    model = Blogger
    paginate_by = 10
class BloggerDetailView(generic.DetailView):
    model = Blogger

    def blogger_detail_view(request, primary_key):
        try:
            blogger = Blogger.objects.get(pk = primary_key)
        except:
            raise Http404('Blogger does not exist')
        return render(request, 'blog/blogger_detail.html', context={'blogger':blogger})

# user list
from django.contrib.auth.mixins import LoginRequiredMixin
class MyArticleUserListView(LoginRequiredMixin,generic.ListView):
    model = Article
    template_name = 'blog/article_list_user.html'
    paginate_by = 10

    def get_queryset(self):
        return Article.objects.filter(blogger__user = self.request.user)
class MyArticleAllUserListView(LoginRequiredMixin,generic.ListView):
    model = Article
    template_name = 'blog/article_list_all_user.html'
    paginate_by = 10

# usercreate
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm
from .forms import RegisterForm
def sign_up(request):
    form = RegisterForm()

    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/accounts/login')
    context = {
        'form':form
    }
    return render(request, 'blog/register.html', context)

# article creat.update.delete
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy, reverse
from .models import Blogger,ArticleInstance
from django import forms
from django.contrib.auth.mixins import PermissionRequiredMixin

class BloggerCreate(CreateView):
    model = Blogger
    fields = '__all__'
    initial = {'date_of_birth':'1999/01/01'}

class ArticleUpdate(PermissionRequiredMixin,UpdateView):
    permission_required = 'blog.can_edit_all_SET'
    model = Article
    fields = '__all__'

class ArticleDelete(DeleteView):
    model = Article
    success_url = reverse_lazy('index')

# comment delete
class ArticleInstanceDelete(DeleteView):
    model = ArticleInstance

    def get_success_url(self):
        # print("test",self.object.article)
        return reverse("article-detail", kwargs={'pk': self.object.article.id})
    

# create comment and article
from django.shortcuts import get_object_or_404
class ArticleInstanceCreate(CreateView):
    model = ArticleInstance
    fields = ['comment']

    def get_context_data(self, **kwargs):
        context = super(ArticleInstanceCreate, self).get_context_data(**kwargs)
        context['article'] = get_object_or_404(Article, pk = self.kwargs['pk'])
        return context
    
    def form_valid(self, form):
        form.instance.commenter = self.request.user
        form.instance.article=get_object_or_404(Article, pk = self.kwargs['pk'])
        return super(ArticleInstanceCreate, self).form_valid(form)
    
    def get_success_url(self):
        pk = self.kwargs["pk"]
        return reverse("article-detail", kwargs={"pk": pk})

class ArticleCreate(CreateView):
    model = Article
    fields = ['title','genre','content']

    def get_context_data(self, **kwargs):
        context = super(ArticleCreate, self).get_context_data(**kwargs)
        context['blogger'] = get_object_or_404(Blogger, pk = self.kwargs['pk'])
        return context
    
    def form_valid(self, form):
        form.instance.article = self.request.user
        form.instance.blogger=get_object_or_404(Blogger, pk = self.kwargs['pk'])
        return super(ArticleCreate, self).form_valid(form)
    
    def get_success_url(self):
        return reverse("article-detail", kwargs={'pk': self.object.id})
    

# class BloggerCreate(CreateView):
#     model = Blogger
#     fields = ['sex','date_of_birth']

#     def get_context_data(self, **kwargs):
#         context = super(ArticleCreate, self).get_context_data(**kwargs)
#         context['user'] = get_object_or_404(Blogger, pk = self.kwargs['pk'])
#         return context
#     def form_valid(self, form):
#         form.instance.article = self.request.user
#         form.instance.user=get_object_or_404(Blogger, pk = self.kwargs['pk'])
#         return super(ArticleCreate, self).form_valid(form)
#     def get_success_url(self):
#         return reverse("article-detail", kwargs={'pk': self.object.id})

MiniBlogDjango/blog/templates/blog/article_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}
{% if perms.blog.can_edit_all_SET %}
<h1>Delete Article</h1>

<p>Are you sure you want to delete the article: {{ article.title }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete." />
</form>
{% else %}
<h2>You do not have permission to access</h2>
{% endif %}

{% endblock %}

MiniBlogDjango/blog/templates/blog/article_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>{{ article.title }}</h1>

  <p><strong>Blogger:</strong> <a href="{% url 'blogger-detail' article.blogger.pk %}">{{ article.blogger }}</a></p> 
  <p><strong>Genre:</strong>{% for genre in article.genre.all %} {{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %}</p></p>
  <p><strong>Issusing Time:</strong> {{ article.issusing_time }}</p>
  <h4><strong>Content:</strong></h4> <p class="text-primary">{{ article.content }}</p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Comments</h4>

    {% for comment in article.articleinstance_set.all %}
    <ul>
        <hr>
        <li><strong>{{ comment.commenter }}</strong> : <a class="text-warning">{{ comment.comment }}</a> - {{ comment.post_time }}
        {% if perms.blog.can_edit_all_SET%}
          <a href="{% url 'comment_delete' comment.pk %}">!!delete!!</a></li>
        {% else %}</li>{% endif %}
    </ul>
    {% endfor %}
    {% if user.is_authenticated %}
    <a href="{% url 'comment_create' article.pk %}">Reply</a>
    {% endif %}
  </div>
{% endblock %}

MiniBlogDjango/blog/templates/blog/article_form.html
{% extends "base_generic.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
</form>
{% endblock %}

MiniBlogDjango/blog/templates/blog/article_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Article List</h1>
  {% if article_list %}
  <ul>
    {% for article in article_list %}
      <li>
        <a href="{{ article.get_absolute_url }}">{{ article.title }}</a> ({{article.blogger}})
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no article in the blog.</p>
  {% endif %}
{% endblock %}

MiniBlogDjango/blog/templates/blog/article_list_all_user.html
{% extends "base_generic.html" %}

{% block content %}
    {% if perms.blog.can_edit_all_SET %}
    <h1>Set Articles</h1>

    {% if article_list %}
    <ul>

      {% for article in article_list %}
      <li>
        <a href="{% url 'article-detail' article.pk %}">{{article.title}}</a> - {{article.issusing_time}}
        <a href="{% url 'article_update' article.pk %}">@update@</a>
        <a href="{% url 'article_delete' article.pk %}">!!delete!!</a>
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no article.</p>
    {% endif %}
    {% else %}
        <h2>You do not have permission to access</h2>
    {% endif %}
{% endblock %}

MiniBlogDjango/blog/templates/blog/article_list_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>My Articles</h1>
    {% if perms.blog.can_create_articles %}
    {% if article_list %}
    <ul>

      {% for article in article_list %}
      <li>
        <a href="{% url 'article-detail' article.pk %}">{{article.title}}</a> - {{article.issusing_time}}
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no article.</p>
    {% endif %}
    {% else %}
    <p>You need a day to get this premission, and you can create your article.</p>
    {% endif %}
{% endblock %}

MiniBlogDjango/blog/templates/blog/articleinstance_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}
{% if perms.blog.can_edit_all_SET %}
<h1>Delete Comment</h1>

<p>Are you sure you want to delete the comment: {{ articleinstance.comment }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete." />
</form>
{% else %}
<h2>You do not have permission to access</h2>
{% endif %}

{% endblock %}

MiniBlogDjango/blog/templates/blog/articleinstance_form.html
{% extends "base_generic.html" %}

{% block content %}
<p>Post your comment for: <a href="{% url 'article-detail' article.pk %}">{{article.title}}</a></p>

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />

</form>
{% endblock %}

MiniBlogDjango/blog/templates/blog/blogger_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Blogger</h1>

<p>Are you sure you want to delete the blogger: {{ blogger }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete." />
</form>

{% endblock %}

MiniBlogDjango/blog/templates/blog/blogger_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Blogger: {{ blogger }}</h1>
  <a> {{ blogger.date_of_birth }}</a>
  <ul>
    <br>
    <h4><a>Articles</a></h4>
        {% for copy in blogger.article_set.all %}
        <hr>
        <li><p><strong>{{ copy.title }} - </strong>{{ copy.genre }} - {{ copy.issusing_time }}</p></li>
        {% endfor %}
      </div>
  </ul>
{% endblock %}

MiniBlogDjango/blog/templates/blog/blogger_form.html
{% extends "base_generic.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />

</form>
{% endblock %}

MiniBlogDjango/blog/templates/blog/blogger_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Blogger List</h1>
  {% if blogger_list %}
  <ul>
    {% for blogger in blogger_list %}
      <li>
        <a href="{{ blogger.get_absolute_url }}">{{ blogger }}</a> ({{blogger.date_of_birth}})
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no blogger.</p>
  {% endif %}
{% endblock %}

MiniBlogDjango/blog/templates/blog/register.html
{% extends 'base_generic.html' %}

{% block content %}

<h1>AuthDev</h1>
<h3>註冊</h3>

<form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}

    <br />
    <input class="btn btn-success" type="submit" value="確認" />
</form>

{% endblock  %}